Repository danielealbano/cachegrand, pull requests merged in 2022-08, with the labels that each got.

#168 Fix sentry support header file and added some tests to cover this little implementation
  docs/configuration.md
  etc/cachegrand.yaml.skel
  src/config_cyaml_schema.c
  src/program.c
  src/support/sentry/sentry_support.c
  src/support/sentry/sentry_support.h
  tests/support/sentry/test-sentry-support.cpp
Labels: bug, enhancement

#172 #171 implement support for storage db entries expirations
  src/clock.c
  src/clock.h
  src/module/redis/command/module_redis_command_mset.c
  src/module/redis/command/module_redis_command_set.c
  src/module/redis/module_redis.c
  src/module/redis/module_redis_connection.c
  src/network/channel/network_channel.c
  src/network/channel/network_channel.h
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  src/worker/network/worker_network_iouring_op.c
  src/worker/network/worker_network_op.c
  tests/test-clock.cpp
  tests/test-program-redis-commands.cpp
  tools/redis-commands-scaffolding-generator/commands.json
Labels: bug, enhancement

#174 Report clock resolution during the bootstrap
  src/clock.c
  src/clock.h
  src/data_structures/hashtable/mcmp/hashtable_op_set.c
  src/program.c
  tests/test-clock.cpp
Labels: enhancement

#175 Update the README.md with a new (functional) SLoC badge and add a new COCOMO badge
  README.md
Labels: bug, enhancement

#176 Update latency charts in readme
  README.md
  docs/benchmarks/cachegrand-amd-epyc-7502p-latencies-2t.png
  docs/benchmarks/cachegrand-amd-epyc-7502p-latencies-64t.png
  docs/benchmarks/cachegrand-amd-epyc-7502p-latencies-t1.jpg
  docs/benchmarks/cachegrand-amd-epyc-7502p-latencies-t64.jpg
Labels: enhancement

#179 Implement support for RMW operations and update the SET command to use them when needed
  src/data_structures/hashtable/mcmp/hashtable.h
  src/data_structures/hashtable/mcmp/hashtable_op_rmw.c
  src/data_structures/hashtable/mcmp/hashtable_op_rmw.h
  src/data_structures/hashtable/mcmp/hashtable_op_set.c
  src/data_structures/hashtable/mcmp/hashtable_op_set.h
  src/data_structures/hashtable/mcmp/hashtable_support_op.c
  src/data_structures/hashtable/mcmp/hashtable_support_op.h
  src/data_structures/hashtable/mcmp/hashtable_support_op_arch.c
  src/data_structures/hashtable/mcmp/hashtable_support_op_arch.h
  src/module/redis/command/module_redis_command_del.c
  src/module/redis/command/module_redis_command_mset.c
  src/module/redis/command/module_redis_command_set.c
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/test-program-redis-commands.cpp
Labels: enhancement

#180 Honor socket keepalive settings
  etc/cachegrand.yaml.skel
  src/network/channel/network_channel.c
  src/network/io/network_io_common.c
  src/network/io/network_io_common.h
  src/worker/network/worker_network_iouring_op.c
  tests/network/io/test-network-io-common.cpp
Labels: enhancement

#183 Redis integration tests launcher
  src/config.c
  src/module/redis/module_redis_command.c
  src/network/channel/network_channel.h
  src/storage/db/storage_db.h
  tests/integration_tests/redis_server/client.tcl
  tests/integration_tests/redis_server/examples/test-example.tcl
  tests/integration_tests/redis_server/helpers.tcl
  tests/integration_tests/redis_server/main.tcl
  tests/integration_tests/redis_server/redis.tcl
  tests/integration_tests/redis_server/server.tcl
  tests/integration_tests/redis_server/test.tcl
Labels: enhancement

#182 Fix receive and send when multiple db chunks are involved
  src/module/prometheus/module_prometheus.c
  src/module/redis/module_redis.c
  src/module/redis/module_redis_command.c
  src/module/redis/module_redis_command.h
  src/network/channel/network_channel.h
  src/network/network.c
  src/random.c
  src/slab_allocator.c
  src/slab_allocator.h
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/test-program-redis-commands.cpp
Labels: bug

#185 Wire in redis integration tests
  .github/workflows/build_and_test.yml
  .github/workflows/report_integration_tests_redis_server.yml
  tests/integration_tests/CMakeLists.txt
  tests/integration_tests/redis_server/CMakeLists.txt
  tests/integration_tests/redis_server/bootstrap.sh
Labels: enhancement

#186 Fix redis-server integration tests reporting
  .github/workflows/report_integration_tests_redis_server.yml
Labels: bug

#187 Hashtable keep track of the keys count
  src/data_structures/hashtable/mcmp/hashtable.c
  src/data_structures/hashtable/mcmp/hashtable.h
  src/data_structures/hashtable/mcmp/hashtable_data.c
  src/data_structures/hashtable/mcmp/hashtable_op_delete.c
  src/data_structures/hashtable/mcmp/hashtable_op_rmw.c
  src/data_structures/hashtable/mcmp/hashtable_op_set.c
  src/data_structures/hashtable/mcmp/hashtable_thread_counters.c
  src/data_structures/hashtable/mcmp/hashtable_thread_counters.h
  src/storage/db/storage_db.c
  tests/unit_tests/modules/prometheus/test-program-prometheus.cpp
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#188 Implement storage db flush sync
  src/data_structures/hashtable/mcmp/hashtable_op_get_key.c
  src/data_structures/hashtable/mcmp/hashtable_op_get_key.h
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
Labels: bug, enhancement

#189 General internal improvements
  src/data_structures/hashtable/mcmp/hashtable_op_iter.c
  src/data_structures/hashtable/mcmp/hashtable_op_iter.h
  src/module/redis/module_redis_command.c
  src/module/redis/module_redis_command.h
  src/module/redis/module_redis_connection.c
  src/module/redis/module_redis_connection.h
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
  tools/redis-commands-scaffolding-generator/generate-commands-scaffolding.py
Labels: enhancement

#191 Fix LCS behaviour when non existant keys are provided
  src/module/redis/command/module_redis_command_lcs.c
  src/module/redis/module_redis_connection.c
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: bug

#192 Implement new command copy
  src/module/redis/command/module_redis_command_copy.c
  src/module/redis/module_redis_connection.c
  src/storage/db/storage_db.c
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#193 Expand used redis tests
  tests/integration_tests/redis_server/bootstrap.sh
Labels: bug, enhancement

#194 Implement expire and persist related commands
  src/module/redis/command/module_redis_command_expire.c
  src/module/redis/command/module_redis_command_expireat.c
  src/module/redis/command/module_redis_command_expiretime.c
  src/module/redis/command/module_redis_command_persist.c
  src/module/redis/command/module_redis_command_pexpire.c
  src/module/redis/command/module_redis_command_pexpireat.c
  src/module/redis/command/module_redis_command_pexpiretime.c
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/integration_tests/redis_server/bootstrap.sh
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#196 Implement GETDEL and GETEX
  src/module/redis/command/module_redis_command_getdel.c
  src/module/redis/command/module_redis_command_getex.c
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#198 Implement getrange and setrange
  src/data_structures/hashtable/spsc/hashtable_spsc.c
  src/data_structures/hashtable/spsc/hashtable_spsc.h
  src/hash/hash_fnv1.h
  src/module/redis/command/module_redis_command_getrange.c
  src/module/redis/command/module_redis_command_setrange.c
  src/module/redis/module_redis.c
  src/module/redis/module_redis_command.c
  src/module/redis/module_redis_command.h
  src/module/redis/module_redis_commands.c
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/unit_tests/data_structures/test-hashtable-spsc.cpp
  tests/unit_tests/modules/redis/test-module-redis-commands.cpp
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#197 Implemented forbidden tags for redis server integration test
  tests/integration_tests/redis_server/bootstrap.sh
  tests/integration_tests/redis_server/examples/test-example.tcl
  tests/integration_tests/redis_server/helpers.tcl
  tests/integration_tests/redis_server/main.tcl
Labels: enhancement

#201 Validate the set, mset, setrange and similar refuse to create empty keys
  src/module/redis/command/module_redis_command_mset.c
  src/module/redis/command/module_redis_command_msetnx.c
  src/module/redis/module_redis_command.c
  src/module/redis/module_redis_connection.c
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: bug

#202 Implement randomkey command
  src/data_structures/hashtable/mcmp/hashtable.h
  src/data_structures/hashtable/mcmp/hashtable_op_delete.c
  src/data_structures/hashtable/mcmp/hashtable_op_get_key.c
  src/data_structures/hashtable/mcmp/hashtable_op_get_random_key.c
  src/data_structures/hashtable/mcmp/hashtable_op_get_random_key.h
  src/data_structures/hashtable/mcmp/hashtable_support_op_arch.c
  src/module/redis/command/module_redis_command_randomkey.c
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  tests/unit_tests/data_structures/hashtable/mpmc/fixtures-hashtable-mpmc.h
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#203 Implement keys command
  src/module/redis/command/module_redis_command_keys.c
  src/module/redis/module_redis_connection.c
  src/module/redis/module_redis_connection.h
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  src/utils_string.c
  src/utils_string.h
  src/utils_string_sw.c
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: enhancement

#204 Refactor the tests for the Redis commands as the unittest file has grown too much and its unmanageable
  tests/unit_tests/modules/redis/command/test-modules-redis-command-copy.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-dbsize.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-del.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-exists.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expire.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expireat.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expiretime.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-fixture.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-fixture.hpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-generic.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-get.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getdel.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getex.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getrange.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getset.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-hello.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-keys.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-lcs.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-mget.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-mset.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-msetnx.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-persist.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpire.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpireat.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpiretime.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-ping.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pttl.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-quit.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-set.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-setrange.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-shutdown.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-touch.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-ttl.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-unlink.cpp
Labels: enhancement

#205 Migrate remaining redis tests and cleanup
  src/module/redis/command/module_redis_command_quit.c
  src/module/redis/command/module_redis_command_shutdown.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-copy.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-dbsize.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-del.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-exists.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expire.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expireat.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-expiretime.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-fixture.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-fixture.hpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-generic.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-get.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getdel.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getex.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getrange.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getset.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-hello.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-keys.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-lcs.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-mget.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-mset.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-msetnx.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-persist.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpire.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpireat.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pexpiretime.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-ping.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-pttl.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-quit.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-set.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-setrange.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-shutdown.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-touch.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-ttl.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-unlink.cpp
  tests/unit_tests/modules/redis/test-program-redis-commands.cpp
Labels: bug, enhancement

#208 General improvements for the existing commands
  src/module/redis/command/module_redis_command_copy.c
  src/module/redis/command/module_redis_command_expire.c
  src/module/redis/command/module_redis_command_expireat.c
  src/module/redis/command/module_redis_command_expiretime.c
  src/module/redis/command/module_redis_command_getset.c
  src/module/redis/command/module_redis_command_lcs.c
  src/module/redis/command/module_redis_command_mget.c
  src/module/redis/command/module_redis_command_msetnx.c
  src/module/redis/command/module_redis_command_persist.c
  src/module/redis/command/module_redis_command_pexpire.c
  src/module/redis/command/module_redis_command_pexpireat.c
  src/module/redis/command/module_redis_command_pexpiretime.c
  src/module/redis/command/module_redis_command_ping.c
  src/module/redis/command/module_redis_command_pttl.c
  src/module/redis/command/module_redis_command_set.c
  src/module/redis/command/module_redis_command_setrange.c
  src/module/redis/command/module_redis_command_touch.c
  src/module/redis/command/module_redis_command_ttl.c
  src/module/redis/module_redis_command.c
Labels: enhancement

#209 Fix invalid expiration time handling in set and getex
  src/module/redis/command/module_redis_command_getex.c
  src/module/redis/command/module_redis_command_set.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-getex.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-set.cpp
Labels: bug

#207 Implemented PSETEX command
  src/module/redis/command/module_redis_command_psetex.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-psetex.cpp
Labels: enhancement

#210 Implement setnx command
  src/module/redis/command/module_redis_command_setnx.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-setnx.cpp
Labels: enhancement

#212 Implement substr command
  src/module/redis/command/module_redis_command_substr.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-substr.cpp
Labels: enhancement

#211 Implement scan command
  src/data_structures/hashtable/mcmp/hashtable_op_rmw.c
  src/module/redis/command/module_redis_command_keys.c
  src/module/redis/command/module_redis_command_scan.c
  src/storage/db/storage_db.c
  src/storage/db/storage_db.h
  src/utils_string.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-scan.cpp
Labels: enhancement

#213 Implement append command
  src/module/redis/command/module_redis_command_append.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-append.cpp
  tests/unit_tests/modules/redis/command/test-modules-redis-command-setrange.cpp
Labels: bug, enhancement

#215 Fix Fedora build instructions
  docs/build-from-source.md
  src/module/redis/CMakeLists.txt
Labels: bug

#214 Implement strlen command
  src/module/redis/command/module_redis_command_strlen.c
  tests/unit_tests/modules/redis/command/test-modules-redis-command-strlen.cpp
Labels: enhancement
